# .super-linter.yml (repo root)

# Only run these
VALIDATE_JSON:        true
VALIDATE_YML:         true
VALIDATE_MD:          true
VALIDATE_TS:          true

# Explicitly turn _off_ the rest
VALIDATE_CHECKOV:           false
VALIDATE_DOCKERFILE_HADOLINT: false
VALIDATE_GITHUB_ACTIONS:     false
# (and so on for any other you don’t want)

# Auto‐fix & more detail
AUTO_FIX:           true
OUTPUT_DETAILS:     true
