# .super-linter.yml

# Core validators you want
VALIDATE_JSON:        true
VALIDATE_MD:          true
VALIDATE_YML:         true
VALIDATE_TS:          true

# Explicitly disable formatters you don’t use
DISABLE_JSON_PRETTIER:       true
DISABLE_MARKDOWN_PRETTIER:   true
DISABLE_YAML_PRETTIER:       true
DISABLE_TYPESCRIPT_PRETTIER: true
DISABLE_JAVASCRIPT_PRETTIER: true

# Explicitly turn off validators you don’t want
VALIDATE_CHECKOV:            false
DISABLE_SHELLCHECK:          true
DISABLE_DOCKERFILE_HADOLINT: true
DISABLE_GITHUB_ACTIONS:      true
DISABLE_JAVASCRIPT_ES:       true

# Meta options
OUTPUT_DETAILS:      true
AUTO_FIX:            true
