# .super-linter.yml

# Core validators
VALIDATE_JSON:           true
VALIDATE_MD:             true
VALIDATE_YML:            true
VALIDATE_TS:             true

# Formatters
VALIDATE_YAML_PRETTIER:  true   # ← enable Prettier for YAML
DISABLE_JSON_PRETTIER:   true   # ← avoid conflicts with VALIDATE_JSON
# (if you ever want Prettier for TS/JS, you can enable VALIDATE_TYPESCRIPT_PRETTIER)

# Disable stuff you don’t need
DISABLE_SHELLCHECK:      true
DISABLE_CHECKOV:         true

# Meta
OUTPUT_DETAILS:          true
AUTO_FIX:                true
