# .super-linter.yml

# 1) Enable the linters you want:
VALIDATE_JSON:        true
VALIDATE_YML:         true
VALIDATE_MD:          true
VALIDATE_TS:          true
# (and any others you actually have code for)

# 2) Disable the ones you don’t need
#    (otherwise it will run Checkov, ShellCheck, Hadolint, etc.)
VALIDATE_CHECKOV:            false
DISABLE_SHELLCHECK:          true
DISABLE_DOCKERFILE_HADOLINT: true
DISABLE_GITHUB_ACTIONS:      true
# …add more DISABLE_* lines here if you don’t want them

# 3) Auto-fix and verbose output
AUTO_FIX:            true
OUTPUT_DETAILS:      true
