name: Lint & Auto-Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # for pushing fixes
  checks:   write   # for status checks

jobs:
  lint:
    name: 🤖 Check only
    runs-on: ubuntu-latest
    permissions:
      contents: read   # just cloning
      checks:   write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter (check)
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  autofix:
    name: ✍️ Auto-Fix & Commit
    needs: lint
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter (auto-fix)
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Enable only the ones you care about
          VALIDATE_JSON:         true
          VALIDATE_YML:          true
          VALIDATE_MD:           true
          VALIDATE_TS:           true

          # Explicitly disable the rest
          VALIDATE_CHECKOV:              false
          VALIDATE_DOCKERFILE_HADOLINT:  false
          VALIDATE_GITHUB_ACTIONS:       false

          AUTO_FIX:            true
          OUTPUT_DETAILS:      true

      - name: Commit & push fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch:           ${{ github.head_ref }}
          commit_message:   chore(lint): apply Super-Linter fixes
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
