# .github/workflows/lint.yml
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  statuses: write

jobs:
  fix-lint-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v8.0.0 # x-release-please-version
        env:
          GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE:    ${{ github.event_name == 'workflow_dispatch' }}
          VALIDATE_JSON:            true
          VALIDATE_YML:             true
          VALIDATE_MD:              true
          VALIDATE_TS:              true
          AUTO_FIX:                 true
          OUTPUT_DETAILS:           true
          SAVE_SUPER_LINTER_OUTPUT:  false
          SAVE_SUPER_LINTER_SUMMARY: false
        
      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        #if: >
        #  github.event_name == 'pull_request' &&
        #  github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
