name: Super-Linter Auto-Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # so we can push branches & PRs
  checks:   write   # so Super-Linter can report status checks

jobs:
  lint-and-fix:
    name: Lint & Auto-Fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter in fix mode
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN:            ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE:   ${{ github.event_name == 'workflow_dispatch' }}

          # only these languages
          VALIDATE_JSON:           true
          VALIDATE_YML:            true
          VALIDATE_MD:             true
          VALIDATE_TS:             true

          # fix and detail outputs
          AUTO_FIX:                true
          OUTPUT_DETAILS:          true

      - name: Create or update lint-fix pull request
        uses: peter-evans/create-pull-request@v6
        with:
          base:            main
          branch:          super-linter-fixes
          title:           chore(lint): apply Super-Linter fixes
          body: |
            This PR applies automatic fixes from Super-Linter.
          commit-message:  chore(lint): apply Super-Linter fixes
          path: |
            **/*.json
            **/*.yml
            **/*.yaml
            **/*.md
            **/*.ts
          draft:           false
          token:           ${{ secrets.GITHUB_TOKEN }}
