name: Super-Linter Auto-Fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # to push branches & PRs
  checks:   write   # so Super-Linter can report status checks

jobs:
  lint-and-fix:
    name: Lint & Auto-Fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter in fix mode
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN:            ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE:   ${{ github.event_name == 'workflow_dispatch' }}
          VALIDATE_JSON:           true
          VALIDATE_YML:            true
          VALIDATE_MD:             true
          VALIDATE_TS:             true
          AUTO_FIX:                true
          OUTPUT_DETAILS:          true

      - name: Clean up Super-Linter output
        run: rm -rf super-linter-output

      - name: Create or update lint-fix Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token:           ${{ secrets.GITHUB_TOKEN }}
          base:            main
          branch:          super-linter-fixes
          title:           chore(lint): apply Super-Linter fixes
          body:            |
                            This pull request applies automatic formatting &  
                            lint fixes from Super-Linter.
          commit-message:  chore(lint): apply Super-Linter fixes
          paths: |
            **/*.json
            **/*.yml
            **/*.yaml
            **/*.md
            **/*.ts
          draft:           false
