# .github/workflows/lint-and-fix.yml
name:Super-Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # to push branches / PRs
  checks:   write   # for Super-Linter status updates

jobs:
  lint-and-fix:
    name: Super-Linter Auto-Fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter in fix mode
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # --- only lint these languages/formats ---
          VALIDATE_JSON:                true
          VALIDATE_YML:                 true
          VALIDATE_MD:                  true
          VALIDATE_TS:                  true

          # --- explicitly disable others to avoid false errors ---
          VALIDATE_CHECKOV:             false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_GITHUB_ACTIONS:      false
          # (add any others you don't need)

          AUTO_FIX:       true
          OUTPUT_DETAILS: true

      - name: Create/Update lint-fix Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          # the branch you want the PR against
          base: main
          # any name you like for the fix branch
          branch: super-linter-fixes
          title: chore(lint): apply Super-Linter fixes
          body: |
            This pull request contains automatic formatting and lint fixes from Super-Linter.
          commit-message: chore(lint): apply Super-Linter fixes
          # only commit files that Super-Linter could have changed
          file-pattern: |
            **/*.json
            **/*.yml
            **/*.yaml
            **/*.md
            **/*.ts
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
