# .github/workflows/lint.yml
name: Super-Linter

on:
  # full-repo lint, manually
  workflow_dispatch:

  # only changed-files lint, on PRs and pushes to main
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: write   # to commit fixes
  checks:   write   # for Super-Linter status updates

jobs:
  lint:
    name: Lint & Auto-Fix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # when run manually, do a full-repo scan; otherwise only changed files
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}

          # pick just the languages you care about:
          VALIDATE_JSON: true
          VALIDATE_YML:  true
          VALIDATE_MD:   true
          VALIDATE_TS:   true

          # disable anything you don’t want:
          VALIDATE_CHECKOV:             false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_GITHUB_ACTIONS:      false

          # auto-fix and show details in the logs
          AUTO_FIX:       true
          OUTPUT_DETAILS: true

      - name: Commit & Push fixes
        if: ${{ steps.lint.outcome == 'success' || steps.lint.outcome == 'failure' }}
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          # push fixes into the same branch (if PR) or create super-linter-fixes
          branch: ${{ github.event_name == 'workflow_dispatch' && 'super-linter-full-scan' || github.head_ref }}
          title:  "chore(lint): apply Super-Linter fixes"
          body: |
            This pull request applies automatic fixes from Super-Linter.
          commit-message: "chore(lint): apply Super-Linter fixes"
          file-pattern: |
            **/*.json
            **/*.yml
            **/*.yaml
            **/*.md
            **/*.ts
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
