name: Update lockfile

on:
  pull_request:
    paths:
      - 'package.json'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.head.repo.full_name == github.repository
      && github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install dependencies & regenerate lockfile
        run: yarn install

      - name: Commit updated lockfile
        uses: peter-evans/create-pull-request@v5
        with:
          base: ${{ github.event.pull_request.head.ref }}
          commit-message: "chore: update lockfile"
          title: "Update lockfile"
          body: |
            This PR was created automatically to update the lockfile after package.json changed.
          labels: |
            dependencies
            automation
          token: ${{ secrets.GITHUB_TOKEN }}
